# Generated by Django 4.1.1 on 2022-09-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('img_school', models.ImageField(upload_to='static')),
                ('discription', models.TextField()),
                ('conatact_no', models.CharField(max_length=11)),
            ],
        ),
    ]
